name: python_data_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - altair
  - hvplot
  - bokeh
  - scikit-learn
  - imbalanced-learn
  - scipy
  - statsmodels
  - jupyterlab
  - notebook
  - ipywidgets
  - black
  - autopep8
  - flake8
  - pip:
      - adjustText
      - anyio
      - beautifulsoup4
      - requests
      - markdown-it-py
      - jsonpointer==2.1
